apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-kafka
  labels:
    app: local-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-kafka
  template:
    metadata:
      labels:
        app: local-kafka
    spec:
      containers:
        - name: local-kafka
          image: confluentinc/cp-kafka:6.2.0
          ports:
            - containerPort: 32181
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "local-zookeeper:32181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:29092"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

