apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-mongo
  labels:
    app: local-mongo
spec:
  selector:
    matchLabels:
      app: local-mongo
  template:
    metadata:
      labels:
        app: local-mongo
    spec:
      containers:
        - name: local-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
